# Stage 1 : compilation avec Maven (tag existant)
FROM maven:3.8.8-openjdk-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2 : runtime
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=builder /app/target/demo-java-app.jar ./demo-java-app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","demo-java-app.jar"]
